### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [4]:
lista = []
k = 0
while len(lista) != 5:
    k += 1
    lista.append(k)
print(lista)

lista2 = []
for i in range(1,6):
    lista2.append(i)
print(lista2)

lista3 = []
for i in lista:
    lista3.append(i)
print(lista3)

list_comprehension = [i for i in range(1,7)]
print(list_comprehension)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [3]:
import numpy as np
#from sympy import isprime

def prime_one_liner(n):
    return True if len([i for i in range(2,n) if n % i == 0]) == 0 else False

# num = 0
# lista = []
# while num != -1:
#     num = int(input())

#     if num != -1 and prime_one_liner(num) :
#         lista.append(num)

lista = [1,2,3,4,5,6,7,8,9,11,13,17]
lista_ripulita = []
for i in lista:
    if prime_one_liner(i):
        lista_ripulita.append(i)

array = np.array(lista_ripulita)
print(array)

array_2 = np.array([i for i in lista if prime_one_liner(i) ])
print(array_2)


[ 1  2  3  5  7 11 13 17]
[ 1  2  3  5  7 11 13 17]


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [ ]:
import numpy as np

lista = [1,2,3,4,5,6,7,8,9,11,13,17]
array_a = np.array(lista)

array_b = array_a[9:12] #np.arange(array_a[9],array_a[11])
print(array_b)

array_c = array_a[::-1]
print(array_c)

array_d = array_a / array_c


[11 13 17]
[17 13 11  9  8  7  6  5  4  3  2  1]
