### **1. Indicizzazione booleana**

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.

2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.

3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista.  


In [ ]:
import numpy as np
def prime_one_liner(n):
    return True if len([i for i in range(2,n) if n % i == 0]) == 0 else False


lista = []
# for i in range[0:21]:
#     if prime_one_liner(i):
#         lista.append(i)

# array_a = np.array(lista)

array_b =np.array([i for i in range[0:21] if prime_one_liner(i)])

for i in array_b:
    if i %2 == 0:
        pass

for i in array_b:
    if i > 10:
        pass




array([False, False, False, False,  True,  True,  True,  True])

### **2.  Operazioni su array**
Crea un array **a**, 2D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.  Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [ ]:
import numpy as np

matrice = np.arange(20).reshape((4, 5))
print(matrice)
array_b = np.array([matrice[1,:], matrice[3,:]]) #b = a[[1, 3], :]
array_b

array_c = np.array([matrice[2,:]]) #c = a[[2], :]

risultato = matrice / array_c
risultato


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[0.        , 0.0625    , 0.11764706, 0.16666667, 0.21052632],
       [0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421],
       [0.66666667, 0.6875    , 0.70588235, 0.72222222, 0.73684211],
       [1.        , 1.        , 1.        , 1.        , 1.        ]])

### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [17]:
import numpy as np

random_2d = np.random.rand(10, 3)
print(random_2d)

distanze = np.abs(0.5 - random_2d)
col_idx = np.argmin(distanze, axis=1)
row_idx = np.arange(10)  

risultato = random_2d[row_idx, col_idx] 
print(risultato)
#lista_colonne = []
# for i in righe:
#     primo = abs((0.5 - float(random_2d[i,1])))
#     secondo = abs((0,5 - random_2d[i,2]))
#     terzo = abs((0,5 - random_2d[i,3]))
#     if primo < secondo and primo < terzo:
#         lista_colonne.append(1)
    
#     if secondo < primo and secondo < terzo:
#         lista_colonne.append(2)
#     if terzo < secondo and terzo < primo:
#         lista_colonne.append(3)
#colonne = np.array(lista_colonne)



[[0.75543416 0.98772102 0.26813884]
 [0.65124359 0.0170169  0.32025623]
 [0.55349495 0.68801688 0.29310684]
 [0.12552583 0.73567316 0.19327699]
 [0.08195207 0.56623217 0.57345024]
 [0.52469097 0.83226572 0.93804003]
 [0.13952829 0.08429881 0.46674449]
 [0.99371523 0.07574152 0.63132106]
 [0.73065087 0.75342511 0.24504056]
 [0.45512518 0.04213865 0.2223868 ]]
[0.26813884 0.65124359 0.55349495 0.73567316 0.56623217 0.52469097
 0.46674449 0.63132106 0.73065087 0.45512518]


### **4. Analisi della Frequenza Cardiaca con NumPy**

1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata:  
   `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
   Inserisci questi valori in un array NumPy.

2. **Trova la frequenza cardiaca minima** registrata durante la giornata.  
   _(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)_

3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
   _(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)_

4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**:  
   - Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
   - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.


In [ ]:
import numpy as np
frequenza_cardiaca = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])
print(frequenza_cardiaca)



f_ordinata = np.sort(frequenza_cardiaca)
print(f_ordinata)
print('Il minimo:', np.min(f_ordinata))
print('Il massimo:',np.max(f_ordinata))

lista = []
true = 0
false = 0
for i in f_ordinata:
    if i > 120:
        lista.append(True)
        true += 1
    else:
        lista.append(False)
        false += 1

#boolean = frequenza_cardiaca > 120 alternativa numpy. crea direttamente il vettore booleano
boolean = np.array(lista)
print(boolean)


percentuale = (true * 100)/len(frequenza_cardiaca)
print(percentuale)

[ 68  65  77 110 160 161 162 161 160 161 162 163 164 163 162 100  90  97
  72  60  70]
[ 60  65  68  70  72  77  90  97 100 110 160 160 161 161 161 162 162 162
 163 163 164]
Il minimo: 60
Il massimo: 164
[False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True  True]
21
21
52.38095238095238


### **5. Manipolazione di vettori**

1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.

3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
Modifica il vettore di conseguenza.

7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?


In [ ]:
import numpy as np

stipendi = np.array([50_000, 105_250, 55_000, 89_000])
save = stipendi.copy()

print(stipendi)

#aumento = np.max(stipendi) + ((np.max(stipendi)*15)/100)
idx_max = np.argmax(stipendi)
stipendi[np.argmax(stipendi)] = np.max(stipendi) + ((np.max(stipendi)*15)/100)
print(stipendi)

idx_min = np.argmin(stipendi)
stipendi[np.argmin(stipendi)] = np.min(stipendi) + ((np.min(stipendi)*20)/100)
print(stipendi)
#ATTENZIONE: Con l'aumento del 20% l'ordine è cambiato, quindi con la soluzione qua sotto viene escluso l'altro dipendendente 
# che non ha ricevuto l'aumento e ne viene dato un altro al vecchio minimo.

# Maschera tutto True, poi escludi min e max
maschera = np.ones(len(stipendi), dtype=bool)
maschera[idx_min] = False
maschera[idx_max] = False
stipendi[maschera] = stipendi[maschera] + ((stipendi[maschera]*10/100))

print(stipendi)

print(sum(stipendi - save))


[ 50000 105250  55000  89000]
[ 50000 121037  55000  89000]
[ 60000 121037  55000  89000]
[ 60000 121037  60500  97900]
40187


### **6. Valori di Co2**

1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

In [ ]:
import numpy as np

emissioni = np.loadtxt('emissioni.txt', delimiter=",", dtype= float)
print(emissioni)
boolean = emissioni > 18
print(np.sum(boolean))
print(np.mean(emissioni[boolean]))

total = np.sum(f'{emissioni[boolean] / np.sum(emissioni)}')
print(total)

[13.62 11.    8.98  8.68 16.37  5.82 15.85 18.25 12.62 16.75  9.64 19.98
 17.36 13.88 15.81 17.48 14.99  5.18 11.48 11.75 13.57 15.62  8.97  7.57
 11.83 17.64 13.81 16.55 13.54 18.29 19.48 18.05  8.35  5.5  14.92  8.7
 18.31 13.41 11.91 17.72  4.68 10.72  6.45 19.62 16.53 19.27 11.03 17.06
 19.33  7.26  4.83  7.83 10.59 10.76 17.35 19.14  7.77  9.79  6.66 18.42
 17.65 14.66 11.19  6.86 15.23 19.    9.92  6.64  7.81  9.83 19.2   7.47
 18.38  7.71  6.18 12.2   6.16 10.7  10.25 14.75 18.53  5.09 17.72  5.26
 18.43  7.08 12.22 19.72 13.9  13.81 11.64 10.82 10.83 11.57  5.2  18.22
  4.44  6.75 12.91  5.53  9.03 11.84  5.54 19.83  6.97 19.71  5.35 17.67
  9.56  7.76  8.08  8.31 12.2  16.37 17.78  7.14  4.35 17.86  5.72 15.65
  6.99 15.23  8.61 16.71 18.07 16.   14.05 19.33  6.38 12.52 14.45 19.31
  8.42  7.13  9.15 17.35  9.5  16.11 12.24 15.08 12.57 16.28  4.39 16.34
 15.97  5.96  4.78  5.26 17.51  7.34 13.62  8.18  9.27 12.83  7.4  13.68
  5.83  4.26 11.45 18.81 11.29 17.65 11.94  5.28 11.

TypeError: unsupported format string passed to numpy.ndarray.__format__

### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


In [61]:
import numpy as np

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])

print(survey_matrix)
survey_matrix[survey_matrix[:,2] >= 12]
print('\n\n\n')
print(survey_matrix[(survey_matrix[:,2] >= 12)]) #punto 1

print(survey_matrix[(survey_matrix[:,2] >= 12), 1]) #punto 2

print(np.mean(survey_matrix[(survey_matrix[:,2] >= 12), 1]))

[[   25 40000    10]
 [   32 52000    12]
 [   40 63000    14]
 [   29 47000    11]
 [   35 58000    13]]




[[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]]
[52000 63000 58000]
57666.666666666664


### **8. Rimpiazzare gli outliers**

Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**.  

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.


In [67]:
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])

ages[ages == 999] = -1
print(ages.max())


112


### 9.**Generazione random di storie**

Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

*"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "__".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza _!" Ci fu grande gioia e celebrazione."*


In [1]:
import numpy as np
import textwrap 
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]

frase = "In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, \" __ \". Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __. Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: \"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza __!\" Ci fu grande gioia e celebrazione."
array = np.array(frase.split())

indici = np.where(array == "__")[0]
for i in indici:
  
    array[i] = np.random.choice(lista_parole)
frase_finale = " ".join(array)
print(textwrap.fill(frase_finale, width=80))

In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico
BENEFICIARIO che proteggeva. Quando un anziano del villaggio venne a chiederle
consiglio su come garantire al meglio un raccolto abbondante e le offrì il
VISIONE come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "
GIUSTIFICAZIO ". Radunò il villaggio e, per i successivi 100 giorni, su sua
richiesta, gli abitanti cercarono nella foresta un __. Nel 101° giorno, il
bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero
dalla donna saggia per donarglielo. Con un sorriso da un orecchio all’altro, e
cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora
è giunto il tempo del banchetto - nessuno rimarrà mai più senza __!" Ci fu
grande gioia e celebrazione.


Esempio di output


"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BIRILLO DA BOWLING. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza GIUSTIFICAZIONE!"  

Ci fu grande gioia e celebrazione."